// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Renders the file upload page",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "Upload page",
                "responses": {
                    "200": {
                        "description": "HTML upload page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/.well-known/agent.json": {
            "get": {
                "description": "Returns structured JSON metadata for AI agent integration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "Agent discovery metadata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.AgentJSON"
                        }
                    }
                }
            }
        },
        "/api/artifacts/{slug}/comments": {
            "get": {
                "description": "Lists whole-artifact threads and threads anchored to the requested site page. Open threads are returned by default.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "List artifact comment threads",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution; send on reads when available",
                        "name": "X-Trove-User-Email",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page path within a multi-page site",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Resolution filter: open, include, or only",
                        "name": "resolved",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.CommentListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a root comment attributed from X-Trove-User-Email. Supports whole-file, element, and text anchors.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Create an artifact comment thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment body and anchor",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comments.CreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/comments.Comment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/artifacts/{slug}/comments/{comment_id}": {
            "delete": {
                "description": "Deletes a comment body while preserving a root tombstone when replies remain. The attribution email must match the original author.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Delete an artifact comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution and author matching",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comment or reply ID",
                        "name": "comment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page path within a multi-page site",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Replaces a comment body. The attribution email must match the original author.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Edit an artifact comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution and author matching",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comment or reply ID",
                        "name": "comment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page path within a multi-page site",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "description": "Replacement body",
                        "name": "edit",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comments.EditInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comments.Comment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/artifacts/{slug}/comments/{comment_id}/replies": {
            "post": {
                "description": "Adds a reply to an open thread.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Reply to an artifact comment thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Root comment ID",
                        "name": "comment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page path within a multi-page site",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "description": "Reply body",
                        "name": "reply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comments.ReplyInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/comments.Comment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/artifacts/{slug}/comments/{comment_id}/resolution": {
            "patch": {
                "description": "Updates the resolution state of a root comment thread.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Resolve or reopen an artifact comment thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Root comment ID",
                        "name": "comment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page path within a multi-page site",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "description": "Desired resolution state",
                        "name": "resolution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comments.ResolveInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comments.Comment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/delete/{slug}": {
            "delete": {
                "description": "Deletes a file by slug. This endpoint is intentionally not exposed via MCP or the UI.",
                "tags": [
                    "admin"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deleted"
                    },
                    "400": {
                        "description": "Missing user email",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/llms.txt": {
            "get": {
                "description": "Returns plain-text API documentation for LLM and agent consumption",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "LLM-friendly API documentation",
                "responses": {
                    "200": {
                        "description": "Plain-text API docs",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mine": {
            "get": {
                "description": "Shows the current user's upload and view history",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "ui"
                ],
                "summary": "User activity dashboard",
                "responses": {
                    "200": {
                        "description": "HTML activity page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload a file and get a shareable link. Supports custom slugs and overwriting existing files.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email used for audit attribution",
                        "name": "X-Trove-User-Email",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Custom URL slug (lowercase alphanumeric and hyphens, 1-64 chars)",
                        "name": "slug",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Set to 'true' to replace an existing file at the same slug",
                        "name": "overwrite",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already taken",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Renders an HTML viewer for the uploaded file (markdown, code, images, CSV, HTML, etc.)",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "View a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML viewer page",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{slug}/raw": {
            "get": {
                "description": "Returns the raw file content with its original content type. Supports Range requests.",
                "tags": [
                    "files"
                ],
                "summary": "Download raw file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "HTTP Range header for partial content",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "206": {
                        "description": "Partial file content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{slug}/{path}": {
            "get": {
                "description": "Returns a file from an uploaded multi-page site",
                "tags": [
                    "files"
                ],
                "summary": "Serve a site asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Site slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path within the site",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_server.AgentEndpoint": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string",
                    "example": "multipart/form-data"
                },
                "description": {
                    "type": "string",
                    "example": "Upload a file. Returns a shareable URL."
                },
                "example": {
                    "type": "string"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_server.AgentEndpointParam"
                    }
                },
                "path": {
                    "type": "string",
                    "example": "/upload"
                },
                "response_example": {
                    "$ref": "#/definitions/cmd_server.UploadResponse"
                }
            }
        },
        "cmd_server.AgentEndpointParam": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The file to upload"
                },
                "name": {
                    "type": "string",
                    "example": "file"
                },
                "required": {
                    "type": "boolean",
                    "example": true
                },
                "type": {
                    "type": "string",
                    "example": "file"
                }
            }
        },
        "cmd_server.AgentJSON": {
            "type": "object",
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://trove.example.com"
                },
                "description": {
                    "type": "string",
                    "example": "File sharing service. Upload any file, get a shareable link."
                },
                "endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_server.AgentEndpoint"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "trove"
                }
            }
        },
        "cmd_server.CommentListResponse": {
            "type": "object",
            "properties": {
                "current_version": {
                    "type": "string"
                },
                "open_thread_count": {
                    "type": "integer"
                },
                "resource": {
                    "type": "string"
                },
                "threads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comments.Thread"
                    }
                }
            }
        },
        "cmd_server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "slug already taken"
                }
            }
        },
        "cmd_server.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "cmd_server.UploadResponse": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string",
                    "example": "my-report"
                },
                "url": {
                    "type": "string",
                    "example": "https://trove.example.com/my-report"
                }
            }
        },
        "comments.Anchor": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "quote": {
                    "$ref": "#/definitions/comments.TextQuote"
                },
                "rect": {
                    "$ref": "#/definitions/comments.Rect"
                },
                "resource": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "selector": {
                    "type": "string"
                },
                "stable_id": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/comments.AnchorType"
                },
                "visible_text": {
                    "type": "string"
                }
            }
        },
        "comments.AnchorType": {
            "type": "string",
            "enum": [
                "file",
                "element",
                "text"
            ],
            "x-enum-varnames": [
                "AnchorFile",
                "AnchorElement",
                "AnchorText"
            ]
        },
        "comments.Comment": {
            "type": "object",
            "properties": {
                "anchor": {
                    "$ref": "#/definitions/comments.Anchor"
                },
                "artifact_version": {
                    "type": "string"
                },
                "author_email": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by_email": {
                    "type": "string"
                },
                "edited_at": {
                    "type": "string"
                },
                "edited_by_email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "string"
                },
                "resolved_by_email": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "thread_id": {
                    "type": "string"
                }
            }
        },
        "comments.CreateInput": {
            "type": "object",
            "properties": {
                "anchor": {
                    "$ref": "#/definitions/comments.Anchor"
                },
                "body": {
                    "type": "string"
                }
            }
        },
        "comments.EditInput": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                }
            }
        },
        "comments.Rect": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                },
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "comments.ReplyInput": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                }
            }
        },
        "comments.ResolveInput": {
            "type": "object",
            "properties": {
                "resolved": {
                    "type": "boolean"
                }
            }
        },
        "comments.TextQuote": {
            "type": "object",
            "properties": {
                "exact": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                }
            }
        },
        "comments.Thread": {
            "type": "object",
            "properties": {
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comments.Comment"
                    }
                },
                "root": {
                    "$ref": "#/definitions/comments.Comment"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "Trove API",
	Description:      "File sharing service. Upload any file, get a shareable link.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
