name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker compose build test

      - name: Run linter
        run: docker compose run --rm lint

      - name: Run tests
        run: docker compose run --rm test

      - name: Run integration tests
        run: HOST_PORT=0 docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm --build integration-test

      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t trove .
